### ISSUE TITLE
Continuation of Cloudflare QUIC Patch

### ISSUE THREAD

**Issue by BrycensRanch** [MaximeMichaud/nginx-autoinstall#1]
Does it really make sense to maintain Cloudflare's QUIC patch for Nginx when Nginx's latest versions support QUIC?

**Comment by MaximeMichaud** [comment]
Hi,

In my opinion, no.
At the moment, HTTP/3 is still a mess tho. (Excluding Caddy/LiteSpeed)

**Comment by MaximeMichaud** [comment]
Hello,

The HTTP/3 implementation in NGINX is now stable and efficient. 
I'm closing this pull request as the Cloudflare patch is no longer needed.

**Comment by BrycensRanch** [comment]
Upgrading all my servers to 1.27.0. Thanks!
